version: '3'

networks:
  springbook:
    external: true

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
  user:
    image: maven:3.8.6-openjdk-11-slim
    container_name: user
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
    volumes:
      - ./user-api/:/var/home/java/user-api/
    command: bash -c " cd /var/home/java/user-api/ && mvn clean package && java -jar /var/home/java/user-api/target/user-api-1.0.jar"
  product:
    image: maven:3.8.6-openjdk-11-slim
    container_name: product
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8081:8081
    volumes:
      - ./product-api/:/var/home/java/product-api/
    command: bash -c " cd /var/home/java/product-api/ && mvn clean package && java -jar /var/home/java/product-api/target/product-api-1.0.jar"
  shoping:
    image: maven:3.8.6-openjdk-11-slim
    container_name: shoping
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8082:8082
    volumes:
      - ./shoping-api/:/var/home/java/shopping-api/
    command: bash -c " cd /var/home/java/shopping-api/ && mvn clean package && java -jar /var/home/java/shopping-api/target/shopping-api-1.0.jar"
